<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AionSniffer</RootNamespace>
    <AssemblyName>AionSniffer</AssemblyName>
    <!-- Npcap (in "WinPcap API-compatible Mode") must be installed on the Windows machine. -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpPcap" Version="6.3.0" />
    <PackageReference Include="PacketDotNet" Version="1.4.7" />
  </ItemGroup>

</Project>
