// Static game knowledge shared by the browser app (i18n.js, app.js) and the server (SEO shells,
// slug backfill) - one file so an instance's English name or boss portrait is never defined twice.
// Plain ESM data, no runtime dependencies. Keys are the literal (English) names as stored in the DB.

export const GAME_NAME_TRANSLATIONS = {
  // Aion 2 instances and bosses in the site's languages (de, fr, es, ru): read from the game client's own
  // text tables (EU client), see Backend/src/data/aion2/*.json _meta.localizedNames.
  "Krao Cave": { en: "Krao Cave", de: "Kraohöhle", fr: "Grotte de Krao", es: "Cueva de Krao", ru: "Пещера крао" },
  "Dying Dramata's Nest": { en: "Dying Dramata's Nest", de: "Nest des Toten Dramatha", fr: "Nid du Dramata Mort", es: "Nido del Dramata Muerto", ru: "Гнездо мертвой драматы" },
  "Fire Temple": { en: "Fire Temple", de: "Feuertempel", fr: "Temple Divin du Feu", es: "Templo de Fuego", ru: "Храм огня" },
  "Draupnir": { en: "Draupnir", de: "Draupnir", fr: "Draupnir", es: "Draupnir", ru: "Драупнир" },
  "Vakron Sky Island": { en: "Vakron Sky Island", de: "Vakrons Luftinsel", fr: "Île Céleste de Vakron", es: "Isla Aérea de Vakron", ru: "Парящий остров Вакрона" },
  "Cradle of Nihility": { en: "Cradle of Nihility", de: "Wiege des Nichts", fr: "Berceau du Néant", es: "Cuna de la Nada", ru: "Колыбель пустоты" },
  "Submerged Life Temple": { en: "Submerged Life Temple", de: "Versunkener Lebenstempel", fr: "Temple Divin de la Vie Englouti", es: "Templo Divino de Vida Hundido", ru: "Затонувший храм жизни" },
  "Shattered Arkanis": { en: "Shattered Arkanis", de: "Zersplitterter Arkanis", fr: "Arcanis Fragmenté", es: "Arkanis Fragmentado", ru: "Расколотый Арканис" },
  "Deus Research Base": { en: "Deus Research Base", de: "Forschungsbasis Deus", fr: "Base de Recherche Deus", es: "Base de Investigación Deus", ru: "Исследовательская база Деус" },
  "Abyssal Forge: Ludra": { en: "Abyssal Forge: Ludra", de: "Abgrundsveredelung: Ludra", fr: "Creuset de l'Abîme : Ludra", es: "Forja Abismal: Ludra", ru: "Закалка пропасти: Рудра" },
  "Hall of Illusion": { en: "Hall of Illusion", de: "Illusionskorridor", fr: "Corridor d'Illusion", es: "Corredor de la Ilusión", ru: "Галерея иллюзий" },
  "Corroded Decontamination Facility": { en: "Corroded Decontamination Facility", de: "Läuterungsstätte der Korrosion", fr: "Sanctuaire de Purification de l'Érosion", es: "Purificatorio de Erosión", ru: "Чистилище скверны" },
  "Urugugu Canyon": { en: "Urugugu Canyon", de: "Uruguguschlucht", fr: "Canyon Urugugu", es: "Cañón de Urugugu", ru: "Ущелье ауругу" },
  "Ferocious Horn Den": { en: "Ferocious Horn Den", de: "Grimmhornhöhle", fr: "Grotte de la Corne Féroce", es: "Caverna del Cuerno Feroz", ru: "Логово Свирепого Рога" },
  "Azure Breath Island": { en: "Azure Breath Island", de: "Insel des Blauatems", fr: "Île du Souffle Azuré", es: "Isla del Aliento Azul", ru: "Остров лазурного дыхания" },
  "Chalice of Muspel": { en: "Chalice of Muspel", de: "Kelch von Muspel", fr: "Calice de Muspel", es: "Cáliz de Muspel", ru: "Чаша Мусфеля" },
  "Mirror of Scarlet Desire": { en: "Mirror of Scarlet Desire", de: "Roter Spiegel des Verlangens", fr: "Miroir de l'Affection Rouge", es: "Espejo de Deseo Rojo", ru: "Красное зеркало тяготения" },
  "Nightmare Altar": { en: "Nightmare Altar", de: "Altar der Albträume", fr: "Autel des Cauchemars", es: "Altar de Pesadilla", ru: "Алтарь кошмара" },
  "Tyrant's Hideout": { en: "Tyrant's Hideout", de: "Versteck des Tyrannen", fr: "Repaire du Tyran", es: "Escondite del Tirano", ru: "Убежище тирана" },
  "Sanctum of Loathing": { en: "Sanctum of Loathing", de: "Sanktuarium des Hasses", fr: "Sanctuaire de la Haine", es: "Sagrario del Odio", ru: "Святилище ненависти" },
  "Depository of Fates": { en: "Depository of Fates", de: "Kammer der Laufbahn", fr: "Dépôt des Trajectoires", es: "Depósito de Trayectoria", ru: "Хранилище траекторий" },
  "Forgotten Repository": { en: "Forgotten Repository", de: "Vergessener Speicher", fr: "Entrepôt Oublié", es: "Repositorio Olvidado", ru: "Забытый тайник" },
  "Chamber of the Dead": { en: "Chamber of the Dead", de: "Schlafstätte der Toten", fr: "Chambre du Mort", es: "Alcoba de los Muertos", ru: "Опочивальня мертвых" },
  "Citadel of the Fallen Daeva": { en: "Citadel of the Fallen Daeva", de: "Zitadelle der gefallenen Daeva", fr: "Citadelle du Daeva déchu", es: "Ciudadela del Daeva Caído", ru: "Цитадель павших даэвов" },
  "Abyssal Horn Den": { en: "Abyssal Horn Den", de: "Abyss-Hornhöhle", fr: "Antre de la Corne abyssale", es: "Guarida del Cuerno Abismal", ru: "Логово рога Бездны" },
  "Pure Spring": { en: "Pure Spring", de: "Quelle der Reinheit", fr: "Fontaine de Pureté", es: "Manantial de Pureza", ru: "Источник чистоты" },
  "Cave of the Stranded": { en: "Cave of the Stranded", de: "Höhle der Gestrandeten", fr: "Grotte des Naufragés", es: "Cueva de los Varados", ru: "Пещера заточенных" },
  "Defunct Creion Laboratory": { en: "Defunct Creion Laboratory", de: "Aufgegebene Versuchsstätte der Creion", fr: "Laboratoire Creion désaffecté", es: "Laboratorio de Creion abandonado", ru: "Заброшенная лаборатория крейонов" },
  "Fallen Haven": { en: "Fallen Haven", de: "Gefallene Zuflucht", fr: "Paradis perdu", es: "Refugio Caído", ru: "Павшее пристанище" },
  "Filthy Cave": { en: "Filthy Cave", de: "Schmutzige Höhle", fr: "Grotte souillée", es: "Cueva Mugrienta", ru: "Грязная пещера" },
  "Cave of the Exiled Ones": { en: "Cave of the Exiled Ones", de: "Höhle der Verbannten", fr: "Grotte des Exilés", es: "Cueva de los Exiliados", ru: "Пещера изгнанников" },
  "Ruthilis of Pain": { en: "Ruthilis of Pain", de: "Ruthilis des Schmerzes", fr: "Ruthilis de la douleur", es: "Ruthilis del dolor", ru: "Руталис боли" },
  "Siliator of Deceit": { en: "Siliator of Deceit", de: "Siliator der Täuschung", fr: "Siliator du mensonge", es: "Siliator de falsedad", ru: "Силиатор лжи" },
  "Talisra of the Void": { en: "Talisra of the Void", de: "Talisra der Leere", fr: "Talisra du Néant", es: "Talisra del vacío", ru: "Талира пустоты" },
  "Thamon": { en: "Thamon", de: "Thamon", fr: "Thamon", es: "Thamon", ru: "Тамон" },
  "Tiere": { en: "Tiere", de: "Tière", fr: "Tiere", es: "Tiere", ru: "Тие" },
  "Vakron": { en: "Vakron", de: "Vakron", fr: "Vakron", es: "Vakron", ru: "Вакрон" },
  "Awakened Alturadon": { en: "Awakened Alturadon", de: "Erwachter Althuradon", fr: "Alturadon éveillé", es: "Alturadon despierto", ru: "Пробудившийся Альтурадон" },
  "Expanding Xyrepe": { en: "Expanding Xyrepe", de: "Expandierender Zairpe", fr: "Zairpe expansif", es: "Zairpe efusivo", ru: "Разбухший Заиреф" },
  "Wise Baumnute": { en: "Wise Baumnute", de: "Weiser Baumnut", fr: "Baumnute le sage", es: "Baumnut prudente", ru: "Мудрый Ваумнут" },
  "Leader Korin": { en: "Leader Korin", de: "Anführer Korin", fr: "Chef Korin", es: "Korin líder", ru: "Вождь Корин" },
  "Eloen": { en: "Eloen", de: "Eloen", fr: "Eloen", es: "Eloen", ru: "Элойн" },
  "Afflicted Bakarma": { en: "Afflicted Bakarma", de: "Gequälter Bakarma", fr: "Bakarma tourmenté", es: "Bakarma agonizante", ru: "Мучающийся Бакрам" },
  "Multiverse Veltiras": { en: "Multiverse Veltiras", de: "Veltiras der Multidimension", fr: "Veltiras multidimensionnelle", es: "Veltiras multidimensional", ru: "Белтирас иных измерений" },
  "Solemn Valkan": { en: "Solemn Valkan", de: "Ehrwürdiger Valkan", fr: "Balkan solennel", es: "Valkan solemne", ru: "Суровый Валкан" },
  "Basilus the False": { en: "Basilus the False", de: "Basilus der Falsche", fr: "Basilus le fourbe", es: "Basilus, el Falso", ru: "Базилус Лживый" },
  "Forbidden Hexbeast Griosa": { en: "Forbidden Hexbeast Griosa", de: "Verbotene Hexbestie Griosa", fr: "Griosa, la bête maudite", es: "Griosa, la Bestia Prohibida de Hex", ru: "Запретный зверь-чернокнижник Гриоса" },
  "Willful Turgen": { en: "Willful Turgen", de: "Willensstarker Turgen", fr: "Turgen l'Indomptable", es: "Turgen, el Obstinado", ru: "Своевольный Турген" },
  "Broodkeeper Nayatman": { en: "Broodkeeper Nayatman", de: "Brutpflegerin Nayatman", fr: "Nayatman d'éclosion", es: "Incubador Nayatman", ru: "Наятман инкубации" },
  "Decaying Durvati": { en: "Decaying Durvati", de: "Korrumpierte Durvati", fr: "Durvati décomposée", es: "Durvati podrido", ru: "Гнилой Дурбати" },
  "Decaying Durvati (Specimen)": { en: "Decaying Durvati (Specimen)", de: "Korrumpierte Durvati (Exemplar)", fr: "Décomposé Durvati (spécimen)", es: "Durvati podrido (espécimen)", ru: "Гнилой Дурбати (образец)" },
  "Durvati's Poison Fluid": { en: "Durvati's Poison Fluid", de: "Durvatis Gift", fr: "Venin de Durvati", es: "Ponzoña de Durvati", ru: "Ядовитая жидкость Дурбати" },
  "Manager Nasium": { en: "Manager Nasium", de: "Verwalter Nasium", fr: "Administrateur Nasium", es: "Administrador Nasium", ru: "Управляющий Назиум" },
  "Mutated Malgerre": { en: "Mutated Malgerre", de: "Mutierter Malgerre", fr: "Malgerre altéré", es: "Malgerre mutado", ru: "Мутировавший Малгерре" },
  "Claudia": { en: "Claudia", de: "Claudia", fr: "Claudia", es: "Claudia", ru: "Клаудия" },
  "Atiel": { en: "Atiel", de: "Atiel", fr: "Atiel", es: "Atiel", ru: "Атиэль" },
  "Gelcos": { en: "Gelcos", de: "Gelcos", fr: "Gelcos", es: "Gelcos", ru: "Гелькос" },
  "Nazmun": { en: "Nazmun", de: "Nazmun", fr: "Nazmun", es: "Nazmun", ru: "Назмун" },
  "Phantasmal Lakshmi": { en: "Phantasmal Lakshmi", de: "Phantom-Lakshmi", fr: "Lakshmi onirique", es: "Lakshmi de ensueño", ru: "Лакшми видения" },
  "Predator Saraswati": { en: "Predator Saraswati", de: "Verschlinger Saraswati", fr: "Saraswati le Prédateur", es: "Saraswati depredador", ru: "Хищница Сарасвати" },
  "Transcendent Bakarma": { en: "Transcendent Bakarma", de: "Transzendierter Bakarma", fr: "Bakarma transcendé", es: "Bakarma trascendido", ru: "Возвышенный Бакрам" },
  "Black Blood Blatt": { en: "Black Blood Blatt", de: "Schwarzblut-Blat", fr: "Blat au sang noir", es: "Blatt de sangre negra", ru: "Блат черной крови" },
  "Devouring Klawfly": { en: "Devouring Klawfly", de: "Schwelgender Klawfly", fr: "Klawfly prédateur", es: "Klawra devorador", ru: "Пожирающий Ньютра" },
  "Surveillance Device": { en: "Surveillance Device", de: "Überwachungsapparat", fr: "Dispositif de surveillance", es: "Dispositivo de vigilancia", ru: "Устройство наблюдения" },
  "Terminator Bargott": { en: "Terminator Bargott", de: "Polymerbargott", fr: "Bargott polymère", es: "Bargott polímero", ru: "Полимерный Багот" },
  "Dhakan": { en: "Dhakan", de: "Dhakan", fr: "Dhakan", es: "Dhakan", ru: "Дхакан" },
  "Gargaum": { en: "Gargaum", de: "Gargaum", fr: "Gargaum", es: "Gargaum", ru: "Гаргаум" },
  "Kapu": { en: "Kapu", de: "Kapu", fr: "Kapu", es: "Kapu", ru: "Капу" },
  "Revenant Tifus": { en: "Revenant Tifus", de: "Rachegeist Tifus", fr: "Tifus revenant", es: "Aparición de Tifus", ru: "Мстительный дух Тифус" },
  "Filthy Grollack": { en: "Filthy Grollack", de: "Schmutziger Grollack", fr: "Grollack le crasseux", es: "Grollack mugriento", ru: "Гроллак-грязнуля" },
  "Karlix": { en: "Karlix", de: "Karlix", fr: "Karlix", es: "Karlix", ru: "Карликс" },
  "Black Smoke Murute": { en: "Black Smoke Murute", de: "Schwarzrauch Murute", fr: "Murute de fumée noire", es: "Humo negro Murute", ru: "Мурт черного дыма" },
  "Kromede's Desire": { en: "Kromede's Desire", de: "Kromedes Gier", fr: "Désir de Kromede", es: "Ambición de Kromede", ru: "Желание Кромед" },
  "Red Spark Ignus": { en: "Red Spark Ignus", de: "Rotflamme Ignus", fr: "Ignus de flamme rouge", es: "Fulgor rojo Ignus", ru: "Игнус красного языка пламени" },
  "Silver Blade Rotan": { en: "Silver Blade Rotan", de: "Silberklinge Rotan", fr: "Rotan à la lame d'argent", es: "Rotan de la cuchilla de plata", ru: "Серебряный рокан" },
  "Enhanced Harcon": { en: "Enhanced Harcon", de: "Verstärkter Harcon", fr: "Harcon amélioré", es: "Harcon mejorado", ru: "Усиленный Харкон" },
  "Neglected Gadioton": { en: "Neglected Gadioton", de: "Vergessener Gadioton", fr: "Gadioton délaissé", es: "Gadioton descuidado", ru: "Брошенный Гадиотон" },
  "Ultimate Berk": { en: "Ultimate Berk", de: "Vollendete Berk", fr: "Berk accomplie", es: "Berk definitivo", ru: "Завершенная форма Берка" },
  "Ferocious Horn Nuakum": { en: "Ferocious Horn Nuakum", de: "Nuakum (Grimmhorn)", fr: "Nuakum à cornes féroces", es: "Nuakum del Cuerno Feroz", ru: "Нуакум свирепого рога" },
  "Necromancer Duanka": { en: "Necromancer Duanka", de: "Nekromantin Duanka", fr: "Duanka nécromancienne", es: "Duanka nigromante", ru: "Некромант Дванка" },
  "Shining Mau Totem": { en: "Shining Mau Totem", de: "Strahlendes Totem (Mau)", fr: "Totem Mau brillant", es: "Tótem de Mau brillante", ru: "Блестящий тотем оборотней" },
  "Watchdog Kwapo": { en: "Watchdog Kwapo", de: "Wachhund Kwapo", fr: "Kwapo le chien de garde", es: "Perro guardián Kwapo", ru: "Сторожевой пес Кухапу" },
  "Kromede's Desolation": { en: "Kromede's Desolation", de: "Kromedes Abgrund", fr: "Abîme de Kromede", es: "Abismo de Kromede", ru: "Пропасть Кромед" },
  "Ordeal of Love": { en: "Ordeal of Love", de: "Prüfung der Liebe", fr: "Épreuve de l'amour", es: "Prueba de amor", ru: "Испытание любви" },
  "Robstino": { en: "Robstino", de: "Robstino", fr: "Robstino", es: "Robstino", ru: "Робстино" },
  "Rotar": { en: "Rotar", de: "Rotar", fr: "Lothar", es: "Rothar", ru: "Лотар" },
  "Blazing Guardian Sword": { en: "Blazing Guardian Sword", de: "Flammendes Hüterschwert", fr: "Épée du gardien flamboyante", es: "Espada guardiana llameante", ru: "Пылающий меч стража" },
  "Iscariel": { en: "Iscariel", de: "Iscariel", fr: "Iscariel", es: "Iscariel", ru: "Искариэль" },
  "Kaldrix": { en: "Kaldrix", de: "Kaldrix", fr: "Kaldrix", es: "Kaldrix", ru: "Калдрикс" },
  "Mutated Elite Chief": { en: "Mutated Elite Chief", de: "Mutierter Elitekommandant", fr: "Commandant d'élite mutant", es: "Jefe de élite mutado", ru: "Мутировавший элитный командир" },
  "Divided Aponos": { en: "Divided Aponos", de: "Fragmentierter Aponos", fr: "Aponos entité fendue", es: "Aponos de fragmentación", ru: "Фрагмент Апноса" },
  "Glassvein": { en: "Glassvein", de: "Glassbane", fr: "Glassvein", es: "Glassvein", ru: "Глесбейн" },
  "Nathara": { en: "Nathara", de: "Nathara", fr: "Nathara", es: "Nathara", ru: "Натхара" },
  "Nazarak": { en: "Nazarak", de: "Nasarak", fr: "Nasarak", es: "Nasarak", ru: "Насарак" },
  "Abyssal Wings Ketu": { en: "Abyssal Wings Ketu", de: "Abgrundsflügel Ketu", fr: "Ketu aux ailes d'Abîme", es: "Alas abismales Ketu", ru: "Крылья пропасти Кету" },
  "Central Abyss Fusion Reactor": { en: "Central Abyss Fusion Reactor", de: "Zentraler Fusionsreaktor (Abgrund)", fr: "Réacteur à fusion central d'Abîme", es: "Reactor de fusión abismal central", ru: "Центральное ядро синтеза пропасти" },
  "Eternal Ludra": { en: "Eternal Ludra", de: "Ludra der Ewigkeit", fr: "Ludra de perpétuité", es: "Ludra de la eternidad", ru: "Рудра веков" },
  "Isolation Specialist Rahu": { en: "Isolation Specialist Rahu", de: "Rahu der Isolation", fr: "Rahu de la disjonction", es: "Rahu aislado", ru: "Раху разрыва" },
  "Featherstorm Duduri": { en: "Featherstorm Duduri", de: "Federsturmduduri", fr: "Duduri au barrage de plumes", es: "Duduri emplumado", ru: "Пернатый Дудури" },
  "Watchful Raptor Dodori": { en: "Watchful Raptor Dodori", de: "Hellwachsamer Raubvogel Dodori", fr: "Dodori rapace aux yeux ouverts", es: "Dodori de corriente torrentosa despierto", ru: "Пробудившийся хищнокрыл Додори" },
  "Water Spirit": { en: "Water Spirit", de: "Wassergeist", fr: "Esprit de l'eau", es: "Espíritu de agua", ru: "Дух воды" },
  "Lamiphedon": { en: "Lamiphedon", de: "Lamiphedon", fr: "Lamiphedon", es: "Lamiphedon", ru: "Ламифедон" },
  "Mau Boss Tshulaga": { en: "Mau Boss Tshulaga", de: "Anführer Tshulaga (Mau)", fr: "Shulag chef Mau", es: "Líder Mau Schlag", ru: "Лидер оборотней Шлаг" },
  "Mau Sentry Soldier": { en: "Mau Sentry Soldier", de: "Wachsoldat (Mau)", fr: "Soldat de guet Mau", es: "Mau vigilante", ru: "Солдат-пограничник оборотней" },
  "Deep Sea Pydeon": { en: "Deep Sea Pydeon", de: "Pydeon der Tiefsee", fr: "Pydeon des profondeurs", es: "Pydeon del mar profundo", ru: "Пайдион пучины" },
  "Singing Ellyde": { en: "Singing Ellyde", de: "Singende Ellyde", fr: "Ellyde chantant", es: "Ellyde del canto", ru: "Поющий Элайд" },
  "Submerged Emon": { en: "Submerged Emon", de: "Versunkener Emon", fr: "Emon englouti", es: "Emon hundido", ru: "Затонувший Эмон" },
  "Menoch": { en: "Menoch", de: "Menox", fr: "Menox", es: "Menoch", ru: "Менокс" },
  "Divine Auldor": { en: "Divine Auldor", de: "Heiliger Auldor", fr: "Auldor sacré", es: "Auldor sagrado", ru: "Священный Аулдор" },
  "Guardian Captain Raur": { en: "Guardian Captain Raur", de: "Hüterhauptmann Raur", fr: "Raur le Capitaine de la garde", es: "Capitán de la Guardia Raur", ru: "Капитан охраны Лаур" },
  "Judge Urahum": { en: "Judge Urahum", de: "Richter Urahum", fr: "Juge Urahum", es: "Juez Urahum", ru: "Судья Урахум" },
};

// Instance photos, keyed by the English instance name. An instance with no entry just renders
// without a photo (icon()'s own onerror-remove handles a bad path the same way) - never guessed.
// Sources: in-game UI screenshots from the Fextralife wiki (the Expedition browser, so some HUD chrome
// survives the poster card's center-crop) and the reveal-article hero images of NCSoft's newsroom
// (about.ncsoft.com), each checked against the article's own text before use.
export const INSTANCE_IMAGES = {
  "Krao Cave": "/images/aion2/instances/krao-cave.png",
  Draupnir: "/images/aion2/instances/draupnir.png",
  "Urugugu Canyon": "/images/aion2/instances/urugugu-canyon.png",
  "Vakron Sky Island": "/images/aion2/instances/vakron-sky-island.png",
  "Fire Temple": "/images/aion2/instances/fire-temple.png",
  "Ferocious Horn Den": "/images/aion2/instances/ferocious-horn-den.png",
  "Cradle of Nihility": "/images/aion2/instances/cradle-of-nihility.jpg",
  "Mirror of Scarlet Desire": "/images/aion2/instances/mirror-of-scarlet-desire.jpg",
  "Chalice of Muspel": "/images/aion2/instances/chalice-of-muspel.jpg",
  "Corroded Decontamination Facility": "/images/aion2/instances/corroded-decontamination-facility.jpg",
  "Submerged Life Temple": "/images/aion2/instances/submerged-life-temple.jpg",
  "Citadel of the Fallen Daeva": "/images/aion2/instances/citadel-of-the-fallen-daeva.jpg",
  "Abyssal Horn Den": "/images/aion2/instances/abyssal-horn-den.jpg",
  "Shattered Arkanis": "/images/aion2/instances/shattered-arkanis.jpg",
  "Deus Research Base": "/images/aion2/instances/deus-research-base.jpg",
  "Sanctum of Loathing": "/images/aion2/instances/sanctum-of-loathing.jpg",
};

// Per-boss art (none yet); a boss without an entry falls back to its instance's photo.
export const BOSS_IMAGES = {};

// Minimum character level to enter, by English instance name - the "Entry requirements" of the game's own
// instance window (EU client list, 2026-10-02). Instances whose level is not known yet have no entry:
// no suffix and no change to their sort position, never a guessed number.
export const INSTANCE_MIN_LEVEL = {
  "Krao Cave": 20,
  "Urugugu Canyon": 28,
  "Fire Temple": 35,
  Draupnir: 45,
  "Ferocious Horn Den": 45,
  "Vakron Sky Island": 45,
};
